import type { Course, Exam, ImportantDate, PlannerData, StudyBlock, Task } from "./types";
import { DEFAULT_DAY_END, DEFAULT_DAY_START } from "./types";
import { isoOffset, jalaliToISO, startOfWeek, toISODate, toJalali } from "./jalali";

function weekIso(offsetFromStart: number, weekStart: PlannerData["weekStart"] = "sat"): string {
  return toISODate(addWeek(offsetFromStart, weekStart));
}

function addWeek(offsetFromStart: number, weekStart: PlannerData["weekStart"]) {
  const start = startOfWeek(new Date(), weekStart);
  const next = new Date(start);
  next.setDate(next.getDate() + offsetFromStart);
  return next;
}

export function createEmptyData(): PlannerData {
  return {
    studentName: "دانشجو",
    academicYear: "۱۴۰۵–۱۴۰۶",
    weekStart: "sat",
    dayStart: DEFAULT_DAY_START,
    dayEnd: DEFAULT_DAY_END,
    courses: [],
    tasks: [],
    blocks: [],
    exams: [],
    importantDates: [],
  };
}

export function createSampleData(): PlannerData {
  const courses: Course[] = [
    { id: "c1", name: "ریاضی عمومی ۲", teacher: "دکتر احمدی", color: "accent" },
    { id: "c2", name: "فیزیک ۱", teacher: "دکتر رضایی", color: "sky" },
    { id: "c3", name: "برنامه‌نویسی پیشرفته", teacher: "دکتر کریمی", color: "ink" },
    { id: "c4", name: "مدارهای منطقی", teacher: "دکتر نوری", color: "mint" },
    { id: "c5", name: "آمار و احتمال", teacher: "دکتر حسینی", color: "sand" },
    { id: "c6", name: "زبان تخصصی", teacher: "استاد محمدی", color: "lilac" },
    { id: "c7", name: "ادبیات فارسی", teacher: "دکتر علوی", color: "blush" },
    { id: "c8", name: "آزمایشگاه فیزیک", teacher: "مهندس صادقی", color: "peach" },
  ];

  const tasks: Task[] = [
    {
      id: "t1",
      title: "تمرین‌های فصل ۳ تا ۵",
      courseId: "c1",
      type: "assignment",
      description: "مسائل زوج کتاب آدامز؛ تحویل دست‌نویس در کلاس",
      priority: "high",
      status: "in_progress",
      dueDate: isoOffset(2),
      dueTime: "12:00",
      grade: null,
      importance: 80,
      notes: "تمرکز روی انتگرال دوگانه و کاربردها",
    },
    {
      id: "t2",
      title: "گزارش آزمایش شماره ۴",
      courseId: "c8",
      type: "report",
      description: "اندازه‌گیری شتاب گرانش با آونگ ساده",
      priority: "medium",
      status: "not_started",
      dueDate: isoOffset(5),
      dueTime: "17:00",
      grade: null,
      importance: 55,
      notes: "حداکثر ۱۲۰۰ کلمه + جدول داده‌ها",
    },
    {
      id: "t3",
      title: "پروژه سامانه کتابخانه",
      courseId: "c3",
      type: "project",
      description: "پیاده‌سازی امانت، رزرو و گزارش‌گیری با React",
      priority: "high",
      status: "in_progress",
      dueDate: isoOffset(21),
      dueTime: "23:59",
      grade: null,
      importance: 95,
      notes: "گیت‌هاب را تا جمعه به‌روز کنید",
    },
    {
      id: "t4",
      title: "کوئیز مدارهای ترکیبی",
      courseId: "c4",
      type: "quiz",
      description: "فصل ۱ تا ۳: گیت، کارنو، جمع‌کننده",
      priority: "high",
      status: "not_started",
      dueDate: isoOffset(3),
      dueTime: "10:00",
      grade: null,
      importance: 70,
      notes: "۲۰ دقیقه — پرسش و پاسخ کوتاه",
    },
    {
      id: "t5",
      title: "مقاله خلاصه مقاله علمی",
      courseId: "c6",
      type: "assignment",
      description: "یک مقاله IEEE را در ۲۰۰ کلمه خلاصه کنید",
      priority: "low",
      status: "done",
      dueDate: isoOffset(-4),
      dueTime: "23:59",
      grade: 18,
      importance: 30,
      notes: "نمره از ۲۰",
    },
    {
      id: "t6",
      title: "ارائه رگرسیون خطی",
      courseId: "c5",
      type: "presentation",
      description: "اسلاید ۱۵ دقیقه‌ای + یک مثال با داده واقعی",
      priority: "medium",
      status: "in_progress",
      dueDate: isoOffset(8),
      dueTime: "14:00",
      grade: null,
      importance: 60,
      notes: "مثال: نمرات میان‌ترم",
    },
    {
      id: "t7",
      title: "مطالعه میان‌ترم فیزیک",
      courseId: "c2",
      type: "study",
      description: "فصل سینماتیک، دینامیک و انرژی",
      priority: "high",
      status: "not_started",
      dueDate: isoOffset(14),
      dueTime: "08:00",
      grade: null,
      importance: 85,
      notes: "روزانه ۴۵ دقیقه مرور",
    },
    {
      id: "t8",
      title: "برگه تمرین ۴ — سری‌ها",
      courseId: "c1",
      type: "assignment",
      description: "همگرایی سری‌های توانی",
      priority: "medium",
      status: "not_started",
      dueDate: isoOffset(-2),
      dueTime: "12:00",
      grade: null,
      importance: 50,
      notes: "عقب افتاده — فردا حتماً تحویل",
    },
    {
      id: "t9",
      title: "تحقیق نیما یوشیج",
      courseId: "c7",
      type: "research",
      description: "تأثیر شعر نو بر ادبیات معاصر",
      priority: "low",
      status: "postponed",
      dueDate: isoOffset(18),
      dueTime: "23:59",
      grade: null,
      importance: 25,
      notes: "منابع: کتاب تاریخ ادبیات",
    },
    {
      id: "t10",
      title: "تمرین درخت دودویی",
      courseId: "c3",
      type: "assignment",
      description: "پیاده‌سازی BST و پیمایش‌ها",
      priority: "medium",
      status: "done",
      dueDate: isoOffset(-6),
      dueTime: "23:59",
      grade: 19,
      importance: 40,
      notes: "کد در ریپو exercises",
    },
    {
      id: "t11",
      title: "آزمایش اندازه‌گیری شتاب",
      courseId: "c8",
      type: "lab",
      description: "حضور در آزمایشگاه و ثبت داده",
      priority: "medium",
      status: "in_progress",
      dueDate: isoOffset(0),
      dueTime: "15:00",
      grade: null,
      importance: 45,
      notes: "روپوش و ماشین‌حساب همراه باشد",
    },
    {
      id: "t12",
      title: "پروژه گروهی ALU چهار بیتی",
      courseId: "c4",
      type: "project",
      description: "طراحی جمع/تفریق و شبیه‌سازی در Logisim",
      priority: "high",
      status: "in_progress",
      dueDate: isoOffset(25),
      dueTime: "23:59",
      grade: null,
      importance: 90,
      notes: "تقسیم کار با همگروهی تا چهارشنبه",
    },
    {
      id: "t13",
      title: "تکلیف آمار سری ۳",
      courseId: "c5",
      type: "assignment",
      description: "توزیع نرمال و فاصله اطمینان",
      priority: "low",
      status: "not_started",
      dueDate: isoOffset(6),
      dueTime: "23:59",
      grade: null,
      importance: 35,
      notes: "",
    },
    {
      id: "t14",
      title: "امتحانک واژگان تخصصی",
      courseId: "c6",
      type: "quiz",
      description: "واژگان فصل ۲ و ۳",
      priority: "medium",
      status: "not_started",
      dueDate: isoOffset(1),
      dueTime: "08:30",
      grade: null,
      importance: 40,
      notes: "فلش‌کارت‌ها را امشب مرور کن",
    },
    {
      id: "t15",
      title: "خلاصه‌نویسی فصل ۲ فیزیک",
      courseId: "c2",
      type: "study",
      description: "قوانین نیوتن و نمودار نیروی آزاد",
      priority: "low",
      status: "done",
      dueDate: isoOffset(-8),
      dueTime: "22:00",
      grade: 17,
      importance: 20,
      notes: "",
    },
    {
      id: "t16",
      title: "ارائه شعر مشروطه",
      courseId: "c7",
      type: "presentation",
      description: "ده دقیقه ارائه کلاسی",
      priority: "medium",
      status: "not_started",
      dueDate: isoOffset(12),
      dueTime: "10:00",
      grade: null,
      importance: 50,
      notes: "اشعار بهار و عارف",
    },
    {
      id: "t17",
      title: "برگه انتگرال معین",
      courseId: "c1",
      type: "assignment",
      description: "۱۰ مسئله از انتگرال معین و کاربرد مساحت",
      priority: "high",
      status: "in_progress",
      dueDate: isoOffset(4),
      dueTime: "12:00",
      grade: null,
      importance: 75,
      notes: "مسئله ۷ و ۹ سخت‌ترند",
    },
    {
      id: "t18",
      title: "گزارش میان‌پروژه",
      courseId: "c3",
      type: "report",
      description: "وضعیت اسپرینت و اسکرین‌شات از صفحات",
      priority: "high",
      status: "not_started",
      dueDate: isoOffset(9),
      dueTime: "23:59",
      grade: null,
      importance: 65,
      notes: "قالب PDF در LMS",
    },
    {
      id: "t19",
      title: "امتحان میان‌ترم ریاضی",
      courseId: "c1",
      type: "exam",
      description: "فصل ۱ تا ۴ — بدون ماشین‌حساب مهندسی",
      priority: "high",
      status: "not_started",
      dueDate: isoOffset(28),
      dueTime: "09:00",
      grade: null,
      importance: 100,
      notes: "آزمون در آمفی‌تئاتر مرکزی",
    },
    {
      id: "t20",
      title: "کوئیز کوتاه فیزیک",
      courseId: "c2",
      type: "quiz",
      description: "حرکت پرتابی",
      priority: "medium",
      status: "done",
      dueDate: isoOffset(-10),
      dueTime: "08:00",
      grade: 16,
      importance: 30,
      notes: "",
    },
  ];

  const blocks: StudyBlock[] = [
    { id: "b1", date: weekIso(0), start: "10:00", end: "12:00", title: "حل تمرین ریاضی", courseId: "c1", notes: "" },
    { id: "b2", date: weekIso(0), start: "14:00", end: "16:00", title: "کدنویسی پروژه", courseId: "c3", notes: "" },
    { id: "b3", date: weekIso(1), start: "10:00", end: "12:00", title: "مرور فیزیک", courseId: "c2", notes: "" },
    { id: "b4", date: weekIso(2), start: "10:00", end: "12:00", title: "مدار منطقی", courseId: "c4", notes: "" },
    { id: "b5", date: weekIso(2), start: "16:00", end: "18:00", title: "آمار — رگرسیون", courseId: "c5", notes: "" },
    { id: "b6", date: weekIso(3), start: "10:00", end: "13:00", title: "اسپرینت پروژه", courseId: "c3", notes: "" },
    { id: "b7", date: weekIso(4), start: "10:00", end: "11:30", title: "زبان تخصصی", courseId: "c6", notes: "" },
    { id: "b8", date: weekIso(5), start: "10:00", end: "12:00", title: "ریاضی — انتگرال", courseId: "c1", notes: "" },
    { id: "b9", date: weekIso(5), start: "15:00", end: "17:00", title: "آزمایشگاه فیزیک", courseId: "c8", notes: "" },
  ];

  const exams: Exam[] = [
    {
      id: "e1",
      title: "میان‌ترم ریاضی عمومی ۲",
      courseId: "c1",
      date: isoOffset(28),
      time: "09:00",
      location: "آمفی‌تئاتر مرکزی",
      notes: "فصل ۱ تا ۴",
      importance: 100,
    },
    {
      id: "e2",
      title: "کوئیز مدارهای منطقی",
      courseId: "c4",
      date: isoOffset(3),
      time: "10:00",
      location: "کلاس ۲۰۴",
      notes: "گیت و کارنو",
      importance: 70,
    },
    {
      id: "e3",
      title: "میان‌ترم فیزیک ۱",
      courseId: "c2",
      date: isoOffset(40),
      time: "08:30",
      location: "سالن امتحانات",
      notes: "سینماتیک تا انرژی",
      importance: 90,
    },
    {
      id: "e4",
      title: "امتحانک زبان تخصصی",
      courseId: "c6",
      date: isoOffset(1),
      time: "08:30",
      location: "کلاس زبان",
      notes: "واژگان",
      importance: 40,
    },
    {
      id: "e5",
      title: "پایان‌پروژه برنامه‌نویسی",
      courseId: "c3",
      date: isoOffset(55),
      time: "16:00",
      location: "دفاع در آزمایشگاه کامپیوتر",
      notes: "ارائه ۱۵ دقیقه‌ای",
      importance: 95,
    },
  ];

  const todayJ = toJalali(new Date());
  const importantDates: ImportantDate[] = [
    { id: "d1", date: isoOffset(0), title: "شروع برنامه‌ریزی ترم", kind: "event" },
    { id: "d2", date: jalaliToISO(todayJ.jy, 7, 1), title: "آغاز سال تحصیلی", kind: "event" },
    { id: "d3", date: isoOffset(3), title: "کوئیز مدارهای منطقی", kind: "exam" },
    { id: "d4", date: isoOffset(21), title: "تحویل پروژه کتابخانه", kind: "deadline" },
    { id: "d5", date: isoOffset(28), title: "میان‌ترم ریاضی", kind: "exam" },
    { id: "d6", date: jalaliToISO(todayJ.jy, 9, 13), title: "تاسوعا", kind: "holiday" },
  ];

  return {
    studentName: "دانشجو",
    academicYear: "۱۴۰۵–۱۴۰۶",
    weekStart: "sat",
    dayStart: DEFAULT_DAY_START,
    dayEnd: DEFAULT_DAY_END,
    courses,
    tasks,
    blocks,
    exams,
    importantDates,
  };
}
